---

version: "3.7"

services:

  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    command: ["consul", "agent", "-config-file=/config/config.hcl", "-config-dir=/config"]
    volumes:
    - "./consul:/config"
    ports:
    - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus.yml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yml
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    ports:
      - "9092:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10
    ports:
      - "3000:3000"

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
